export const booths = [
    {
        boothNumber: 'A01',
        top: 10,
        left: 10,
        width: 20,
        height: 20,
        fill: 'white',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Grunt Style'
    },
    {
        boothNumber: 'A02',
        top: 30,
        left: 10,
        width: 20,
        height: 20,
        fill: 'white',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'ATP'
    },
    {
        boothNumber: 'A03',
        top: 50,
        left: 10, 
        width: 20,
        height: 20,
        fill: 'white',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'ALPINEXXX'
    },
    {
        boothNumber: 'A04',
        top: 70,
        left: 10,
        width: 20,
        height: 20,
        fill: 'white',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Yeti'
    },
    {
        boothNumber: 'A05',
        top: 90,
        left: 10, 
        width: 20,
        height: 20,
        fill: 'white',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'ALPINEXXX'
    },
    {
        boothNumber: 'A06',
        top: 110,
        left: 10,
        width: 20,
        height: 20,
        fill: 'white',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Yeti'
    },
    {
        boothNumber: 'A07',
        top: 130,
        left: 10, 
        width: 20,
        height: 20,
        fill: 'white',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'ALPINEXXX'
    },
    {
        boothNumber: 'A08',
        top: 150,
        left: 10,
        width: 20,
        height: 20,
        fill: 'white',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Yeti'
    },
    {
        boothNumber: 'A09',
        top: 170,
        left: 10, 
        width: 20,
        height: 20,
        fill: 'white',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'ALPINEXXX'
    },
    {
        boothNumber: 'A10',
        top: 190,
        left: 10,
        width: 20,
        height: 20,
        fill: 'white',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Yeti'
    },
    {
        boothNumber: 'B01',
        top: 10,
        left: 40,
        width: 20,
        height: 20,
        fill: 'yellow',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'B02',
        top: 30,
        left: 40,
        width: 20,
        height: 20,
        fill: 'yellow',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'B03',
        top: 50,
        left: 40,
        width: 20,
        height: 20,
        fill: 'yellow',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'B04',
        top: 70,
        left: 40,
        width: 20,
        height: 20,
        fill: 'yellow',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'B05',
        top: 90,
        left: 40,
        width: 20,
        height: 20,
        fill: 'yellow',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'B06',
        top: 110,
        left: 40,
        width: 20,
        height: 20,
        fill: 'yellow',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'B07',
        top: 130,
        left: 40,
        width: 20,
        height: 20,
        fill: 'yellow',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'B08',
        top: 150,
        left: 40,
        width: 20,
        height: 20,
        fill: 'yellow',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'B09',
        top: 170,
        left: 40,
        width: 20,
        height: 20,
        fill: 'yellow',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'B10',
        top: 190,
        left: 40,
        width: 20,
        height: 20,
        fill: 'yellow',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'C01',
        top: 10,
        left: 70,
        width: 20,
        height: 20,
        fill: 'pink',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'C02',
        top: 30,
        left: 70,
        width: 20,
        height: 20,
        fill: 'pink',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'C03',
        top: 50,
        left: 70,
        width: 20,
        height: 20,
        fill: 'pink',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'C04',
        top: 70,
        left: 70,
        width: 20,
        height: 20,
        fill: 'pink',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'C05',
        top: 90,
        left: 70,
        width: 20,
        height: 20,
        fill: 'pink',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'C06',
        top: 110,
        left: 70,
        width: 20,
        height: 20,
        fill: 'pink',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'C07',
        top: 130,
        left: 70,
        width: 20,
        height: 20,
        fill: 'pink',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'C08',
        top: 150,
        left: 70,
        width: 20,
        height: 20,
        fill: 'pink',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'C09',
        top: 170,
        left: 70,
        width: 20,
        height: 20,
        fill: 'pink',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'C10',
        top: 190,
        left: 70,
        width: 20,
        height: 20,
        fill: 'pink',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'D01',
        top: 10,
        left: 100,
        width: 20,
        height: 20,
        fill: 'lightblue',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'D02',
        top: 30,
        left: 100,
        width: 20,
        height: 20,
        fill: 'lightblue',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'D03',
        top: 50,
        left: 100,
        width: 20,
        height: 20,
        fill: 'lightblue',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'D04',
        top: 70,
        left: 100,
        width: 20,
        height: 20,
        fill: 'lightblue',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'D05',
        top: 90,
        left: 100,
        width: 20,
        height: 20,
        fill: 'lightblue',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'D06',
        top: 110,
        left: 100,
        width: 20,
        height: 20,
        fill: 'lightblue',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'D07',
        top: 130,
        left: 100,
        width: 20,
        height: 20,
        fill: 'lightblue',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'D08',
        top: 150,
        left: 100,
        width: 20,
        height: 20,
        fill: 'lightblue',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'D09',
        top: 170,
        left: 100,
        width: 20,
        height: 20,
        fill: 'lightblue',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    },
    {
        boothNumber: 'D10',
        top: 190,
        left: 100,
        width: 20,
        height: 20,
        fill: 'lightblue',
        stroke: 'lightgray',
        strokeWidth: 1,
        vendor: 'Party Supplies Inc.'
    }
    
]